# -*- coding: utf-8 -*-
"""Grade_Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nd2K2qhpbGzlFVdlR_4GfEe_Teb3nZP2
"""

from statistics import mode, median, mean
scores = []
while True:
  scores_input = input(" Enter score: ('done'):")
  if scores_input == "done":
    break
  scores_input = int(scores_input)
  scores.append(scores_input)
average_value =mean(scores)
middle_value =mode(scores)
comman_value =median(scores)

print(f"average: {average_value}")
print(f"middle: {middle_value}")
print(f"comman: {comman_value}")

if average_value > 85:
  print(f"Excellent!")
elif average_value >= 75:
  print(f"Better! Need more work!")
else:
  print(f"Average!")